title: Mike Veltman
description: Personal site of Mike Veltman — photography, music and more.
og_image: /assets/pantropica/green.jpeg
url: https://mikeveltman.nl

include: ['_pages']
exclude: ['_notes']

baseurl: ''
open_external_links_in_new_tab: true
permalink: /blog/:title/

plugins:
  - jekyll-last-modified-at

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

sass:
  sass_dir: _sass
  style: :compressed

collections:
  projects:
    output: true
    permalink: /projects/:slug/

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
